import React, { useState, useEffect } from 'react';
import {
  ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';

import AppShell from '../../components/AppShell';
import { colors } from '../../constants/colors';
import { globalHeight, globalWidth } from '../../constants/globalWidth';
import {
  getSalesChannelById,
  createSalesChannel,
  updateSalesChannel,
} from '../../store/salesChannels/salesChannelActions';

/* ─── Helpers ───────────────────────────────────────────────────────────── */
function toKey(name) {
  return String(name || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function Field({ label, required, hint, error, children }) {
  return (
    <View style={styles.field}>
      <Text style={styles.fieldLabel}>
        {label}
        {required && <Text style={styles.required}> *</Text>}
      </Text>
      {children}
      {hint ? <Text style={styles.fieldHint}>{hint}</Text> : null}
      {error ? <Text style={styles.fieldError}>{error}</Text> : null}
    </View>
  );
}

function Toggle({ label, value, onChange, description }) {
  return (
    <Pressable style={styles.toggleRow} onPress={() => onChange(!value)}>
      <View style={styles.toggleInfo}>
        <Text style={styles.toggleLabel}>{label}</Text>
        {description ? <Text style={styles.toggleDesc}>{description}</Text> : null}
      </View>
      <View style={[styles.toggleTrack, value && styles.toggleTrackOn]}>
        <View style={[styles.toggleThumb, value && styles.toggleThumbOn]} />
      </View>
    </Pressable>
  );
}

/* ─── Main ──────────────────────────────────────────────────────────────── */
export default function SalesChannelFormScreen({ navigation, route, userDetails, appMetadata, onSignOut }) {
  const mode = route?.params?.mode || 'create';
  const channelId = route?.params?.channelId;
  const isEdit = mode === 'edit' && !!channelId;
  const token = userDetails?.token || userDetails?.data?.token || '';

  const [loadingInit, setLoadingInit] = useState(isEdit);
  const [saving, setSaving] = useState(false);
  const [loadError, setLoadError] = useState('');
  const [saveError, setSaveError] = useState('');
  const [saveMessage, setSaveMessage] = useState('');
  const [keyAutoGenerated, setKeyAutoGenerated] = useState(!isEdit);

  const [form, setForm] = useState({
    channelName: '',
    channelKey: '',
    description: '',
    focEnabled: true,
    allowRepOrders: false,
    status: 'active',
    isActive: true,
  });
  const [errors, setErrors] = useState({});

  const set = (key) => (val) => setForm((f) => ({ ...f, [key]: val }));

  useEffect(() => {
    if (!isEdit) return;
    setLoadingInit(true);
    getSalesChannelById(token, channelId)
      .then((data) => {
        setForm({
          channelName: data?.channelName || '',
          channelKey: data?.channelKey || '',
          description: data?.description || '',
          focEnabled: data?.focEnabled !== false,
          allowRepOrders: data?.allowRepOrders === true,
          status: data?.status || 'active',
          isActive: data?.isActive !== false,
        });
        setKeyAutoGenerated(false);
      })
      .catch((e) => setLoadError(e.message || 'Failed to load channel'))
      .finally(() => setLoadingInit(false));
  }, [isEdit, channelId, token]);

  const handleNameChange = (val) => {
    set('channelName')(val);
    if (keyAutoGenerated) {
      set('channelKey')(toKey(val));
    }
  };

  const handleKeyChange = (val) => {
    setKeyAutoGenerated(false);
    set('channelKey')(val.toLowerCase().replace(/[^a-z0-9_]/g, ''));
  };

  const validate = () => {
    const errs = {};
    if (!form.channelName.trim()) errs.channelName = 'Channel name is required';
    setErrors(errs);
    return Object.keys(errs).length === 0;
  };

  const handleSave = async () => {
    if (!validate()) return;
    setSaving(true);
    setSaveError('');
    setSaveMessage('');
    try {
      const payload = {
        channelName: form.channelName.trim(),
        channelKey: form.channelKey.trim() || toKey(form.channelName),
        description: form.description.trim(),
        focEnabled: form.focEnabled,
        allowRepOrders: form.allowRepOrders,
        status: form.status,
        isActive: form.isActive,
      };
      if (isEdit) {
        await updateSalesChannel(token, channelId, payload);
        setSaveMessage('Channel updated successfully.');
      } else {
        await createSalesChannel(token, payload);
        setSaveMessage('Channel created successfully.');
      }
      setTimeout(() => navigation.navigate('SalesChannels'), 900);
    } catch (e) {
      setSaveError(e.message || 'Failed to save channel');
    } finally {
      setSaving(false);
    }
  };

  return (
    <AppShell
      userDetails={userDetails}
      appMetadata={appMetadata}
      onSignOut={onSignOut}
      activeRoute="SalesChannels"
    >
      {/* Breadcrumb */}
      <View style={styles.breadcrumb}>
        <Pressable onPress={() => navigation.navigate('SalesChannels')}>
          <Text style={styles.breadLink}>Sales Channels</Text>
        </Pressable>
        <Ionicons name="chevron-forward" size={13} color={colors.textMuted} />
        <Text style={styles.breadCurrent}>{isEdit ? 'Edit Channel' : 'New Channel'}</Text>
      </View>

      {loadingInit ? (
        <View style={styles.centered}><ActivityIndicator size="small" color={colors.primary} /></View>
      ) : loadError ? (
        <View style={styles.centered}><Text style={styles.errorText}>{loadError}</Text></View>
      ) : (
        <View style={styles.formCard}>
          <Text style={styles.cardTitle}>{isEdit ? 'Edit Sales Channel' : 'New Sales Channel'}</Text>
          <Text style={styles.cardSubtitle}>
            {isEdit
              ? 'Update the channel details below.'
              : 'Create a new sales channel. The channel key is used internally and auto-generated from the name if left empty.'}
          </Text>

          <View style={styles.twoCol}>
            {/* Left column */}
            <View style={styles.col}>
              <Field label="Channel Name" required error={errors.channelName}>
                <TextInput
                  style={[styles.input, errors.channelName && styles.inputError]}
                  value={form.channelName}
                  onChangeText={handleNameChange}
                  placeholder="e.g. Direct, UPP, Institutional"
                  placeholderTextColor={colors.textMuted}
                />
              </Field>

              <Field
                label="Channel Key"
                hint={
                  keyAutoGenerated
                    ? 'Auto-generated from channel name. Edit to override.'
                    : 'Internal key — lowercase letters, numbers, underscores only.'
                }
              >
                <View style={styles.keyInputRow}>
                  <TextInput
                    style={[styles.input, styles.keyInput]}
                    value={form.channelKey}
                    onChangeText={handleKeyChange}
                    placeholder="e.g. direct, upp, institutional"
                    placeholderTextColor={colors.textMuted}
                    autoCapitalize="none"
                  />
                  {keyAutoGenerated && (
                    <View style={styles.autoBadge}>
                      <Text style={styles.autoBadgeText}>auto</Text>
                    </View>
                  )}
                </View>
              </Field>

              <Field label="Description">
                <TextInput
                  style={[styles.input, styles.inputMulti]}
                  value={form.description}
                  onChangeText={set('description')}
                  placeholder="Optional description of this channel"
                  placeholderTextColor={colors.textMuted}
                  multiline
                  numberOfLines={3}
                  textAlignVertical="top"
                />
              </Field>
            </View>

            {/* Right column */}
            <View style={styles.col}>
              <Text style={styles.sectionLabel}>Channel Settings</Text>

              <Toggle
                label="FOC Enabled"
                description="Allow setting a Free-of-Charge percentage for products in this channel."
                value={form.focEnabled}
                onChange={(v) => setForm((f) => ({ ...f, focEnabled: v }))}
              />

              <View style={styles.divider} />

              <Toggle
                label="Allow medical reps to create orders in this channel"
                description="When enabled, this channel appears in order creation."
                value={form.allowRepOrders}
                onChange={(v) => setForm((f) => ({ ...f, allowRepOrders: v }))}
              />

              <View style={styles.divider} />

              <Toggle
                label="Active"
                description="Inactive channels cannot be assigned to products."
                value={form.isActive}
                onChange={(v) => setForm((f) => ({
                  ...f,
                  isActive: v,
                  status: v ? 'active' : 'inactive',
                }))}
              />

              <View style={styles.divider} />

              {/* Info box */}
              <View style={styles.infoBox}>
                <Ionicons name="information-circle-outline" size={15} color={colors.primary} />
                <Text style={styles.infoText}>
                  Once a channel is assigned to products, its <Text style={styles.infoBold}>Channel Key</Text> should not be changed as it is referenced in bulk imports.
                </Text>
              </View>

              {saveError ? <Text style={styles.errorText}>{saveError}</Text> : null}
              {saveMessage ? <Text style={styles.successText}>{saveMessage}</Text> : null}

              <View style={styles.actionRow}>
                <Pressable style={styles.btnCancel} onPress={() => navigation.goBack()}>
                  <Text style={styles.btnCancelText}>Cancel</Text>
                </Pressable>
                <Pressable style={styles.btnPrimary} onPress={handleSave} disabled={saving}>
                  {saving && <ActivityIndicator size={14} color={colors.white} />}
                  <Text style={styles.btnPrimaryText}>
                    {saving ? 'Saving...' : isEdit ? 'Update Channel' : 'Create Channel'}
                  </Text>
                </Pressable>
              </View>
            </View>
          </View>
        </View>
      )}
    </AppShell>
  );
}

/* ─── Styles ────────────────────────────────────────────────────────────── */
const shadow = { shadowColor: '#0B2B66', shadowOpacity: 0.06, shadowRadius: 8, shadowOffset: { width: 0, height: 2 } };

const styles = StyleSheet.create({
  breadcrumb: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: globalHeight('1.2%') },
  breadLink: { fontSize: 13, color: colors.primary, fontWeight: '600' },
  breadCurrent: { fontSize: 13, color: colors.textSecondary },

  formCard: {
    borderWidth: 1, borderColor: colors.border, borderRadius: 10,
    backgroundColor: colors.surface, padding: 24, ...shadow,
  },
  cardTitle: { fontSize: 17, fontWeight: '800', color: colors.textPrimary, marginBottom: 4 },
  cardSubtitle: { fontSize: 13, color: colors.textSecondary, marginBottom: 24 },

  twoCol: { flexDirection: 'row', gap: 32, alignItems: 'flex-start' },
  col: { flex: 1, gap: 18, minWidth: 0 },

  sectionLabel: {
    fontSize: 13, fontWeight: '800', color: colors.textSecondary,
    textTransform: 'uppercase', marginBottom: -6,
  },

  field: { gap: 6 },
  fieldLabel: { fontSize: 13, fontWeight: '700', color: colors.textPrimary },
  required: { color: colors.danger },
  fieldHint: { fontSize: 11, color: colors.textMuted },
  fieldError: { fontSize: 12, color: colors.danger },

  input: {
    borderWidth: 1, borderColor: colors.border, borderRadius: 8,
    paddingHorizontal: 12, height: 40, fontSize: 13, color: colors.textPrimary,
    backgroundColor: colors.surface, outlineStyle: 'none',
  },
  inputError: { borderColor: colors.danger },
  inputMulti: { height: 80, paddingTop: 10 },

  keyInputRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  keyInput: { flex: 1, fontFamily: 'monospace' },
  autoBadge: {
    borderWidth: 1, borderColor: '#BFDBFE', borderRadius: 6,
    paddingHorizontal: 8, paddingVertical: 3, backgroundColor: '#EFF6FF',
  },
  autoBadgeText: { color: '#1D4ED8', fontSize: 11, fontWeight: '700' },

  toggleRow: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingVertical: 12,
  },
  toggleInfo: { flex: 1, paddingRight: 16 },
  toggleLabel: { fontSize: 14, fontWeight: '700', color: colors.textPrimary },
  toggleDesc: { fontSize: 12, color: colors.textSecondary, marginTop: 2 },
  toggleTrack: {
    width: 44, height: 24, borderRadius: 12,
    backgroundColor: colors.border, padding: 2,
    justifyContent: 'center',
  },
  toggleTrackOn: { backgroundColor: colors.primary },
  toggleThumb: {
    width: 20, height: 20, borderRadius: 10,
    backgroundColor: colors.white,
    shadowColor: '#000', shadowOpacity: 0.15, shadowRadius: 2, shadowOffset: { width: 0, height: 1 },
  },
  toggleThumbOn: { alignSelf: 'flex-end' },

  divider: { height: 1, backgroundColor: colors.border },

  infoBox: {
    flexDirection: 'row', gap: 8, alignItems: 'flex-start',
    backgroundColor: '#EFF6FF', borderWidth: 1, borderColor: '#BFDBFE',
    borderRadius: 8, padding: 12,
  },
  infoText: { flex: 1, fontSize: 12, color: colors.textSecondary, lineHeight: 18 },
  infoBold: { color: colors.textPrimary, fontWeight: '700' },

  actionRow: {
    flexDirection: 'row', justifyContent: 'flex-end', gap: 10,
    paddingTop: 16, borderTopWidth: 1, borderTopColor: colors.border,
  },
  btnPrimary: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    backgroundColor: colors.primary, paddingHorizontal: 18, paddingVertical: 9, borderRadius: 8,
  },
  btnPrimaryText: { color: colors.white, fontSize: 13, fontWeight: '700' },
  btnCancel: {
    paddingHorizontal: 18, paddingVertical: 9,
    borderRadius: 8, borderWidth: 1, borderColor: colors.border,
  },
  btnCancelText: { fontSize: 13, color: colors.textSecondary, fontWeight: '700' },

  centered: { alignItems: 'center', padding: 32, gap: 10 },
  errorText: { color: colors.danger, fontSize: 13 },
  successText: { color: colors.success, fontSize: 13, fontWeight: '700' },
});
